### ISSUE TITLE
Lost Realtime Events

### ISSUE THREAD

**Issue by discorick** [huboard/huboard-web#226] opened 2016-03-08 21:10 UTC
Under certain circumstances real time events can be lost causing boards to fall out if sync with GitHub. 

One obvious reproduction of this is when a browser is closed and reopened later, a saved HuBoard tab will reopen to the last know state, but the events required to sync up are long gone - this can be chaotic for users during morning stand ups and meetings. 

I suspect (but have not confirmed) this can also happen when a tab is either left unattended for long periods of time, or a system has been left in sleep mode. One of our users reports:

> There is something seriously wrong with Huboard's synching with GitHub. Even when I'm actively using Huboard it does not resynch my browser session with GitHub. I'm constantly finding myself in situations where my guys are asking me to look at a bug and when I query for it, it doesn't show up in Huboard. I have to do a full refresh before I will find it. Really frustrating.

Also Relates to missing Events: https://github.com/huboard/huboard/issues/598
Closes https://github.com/huboard/huboard/issues/214

Task List:

- [x] Implement Sticky Toasts, and Stateful Progress Toasts
- [ ] After a period of inactivity, run a diff on the browser on focus to determine if any events have been missed
    - Track the last X number of events processed
    - If events are missing, and not past the X threshold, fetch the missed events and play them on the client
    - Disable board use during any syncing activity
  - If events are missing and are past X threshold, prompt for page refresh

**Comment by seanlinsley** [comment] 2016-03-08 21:14
I've also noticed that PRs created an tickets reopened require a refresh before they show up. But perhaps that should be a separate ticket?

**Comment by seanlinsley** [comment] 2016-03-08 21:15
For this ticket itself, I especially seem to notice the loss of events when my computer has been asleep.

**Comment by discorick** [comment] 2016-03-08 21:17
@seanlinsley I know what you mean, this is a blind spot in our webhook coverage - it's documented in another issue but I will make sure to link it here, as all of these problems should be addressed as quickly as possible 

> For this ticket itself, I especially seem to notice the loss of events when my computer has been asleep.
Thanks for the confirmation!

**Comment by yaronyg** [comment] 2016-03-09 01:20
I was the one quoted above and for what it's worth this repo's for me every single day. Every day when I run the stand up for my group my Firefox browser window, which was left open all night, will show out of date info and I have to refresh. But even during the day as I manage bugs directly through GitHub I can be sure I won't see the update in my Huboard window.

But this bug also happens when I'm actively using Huboard. For example, I opened a PR in Huboard, clicked on the link to Reviewable, finished the review, clicked in Reviewable to link to GitHub to assign the PR back to the dev who submitted, switched to Huboard (which I would have last used in this case maybe 30 minutes before) and sure enough the PR still showed as assigned to me. I left the window open all day and it never updated. Finally I hit refresh and sure enough, the bug was gone.

At this point I treat Huboard as a static view and every single time I go to it I hit refresh. :(

**Comment by dahlbyk** [comment] 2016-03-09 16:56
Are we using the [Events API](https://developer.github.com/v3/activity/events/) anywhere? If the socket drops, or periodically if the board has been unfocused for a while, we should be able to use that to true up more efficiently than a full reload.

https://api.github.com/repos/huboard/huboard-web/events

**Comment by dahlbyk** [comment] 2016-03-09 20:24
Related: https://github.com/huboard/huboard/issues/214

**Comment by discorick** [comment] 2016-03-22 15:35
Leaving HuBoard running in a Chrome tab overnight and checking it the next morning:

![uploads/e0737de9-aecf-405d-86f5-4ed53d941da8/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe0737de9-aecf-405d-86f5-4ed53d941da8%2Fblob)

The interesting error is `Failed to load resource: net::ERR_TIMED_OUT`

**Comment by yaronyg** [comment] 2016-03-22 17:00
Does anyone on Firefox EVER get any updates? At this point if I do something in Github it will never show up in Huboard until I do a full refresh. Only changes made in Huboard (by myself or others) actually show up.

**Comment by dahlbyk** [comment] 2016-03-24 17:18
> Does anyone on Firefox EVER get any updates? At this point if I do something in Github it will never show up in Huboard until I do a full refresh. Only changes made in Huboard (by myself or others) actually show up.

I just tested this with https://github.com/rauhryan/skipping_stones_repo/issues/340#event-602059085 and got the update in Firefox:
<img width="520" alt="firefox_2016-03-24_12-16-09" src="https://cloud.githubusercontent.com/assets/133987/14025109/59a1d87a-f1ba-11e5-9e9e-648717f5178a.png">

However, I did _just_ open HuBoard to that repo. I suspect that by leaving the window open I'll eventually lose the socket connection and stop getting updates.

**Comment by yaronyg** [comment] 2016-03-24 18:17
@dahlbyk Yup, sometimes I"ll see things right after the window is open but that is it. It's super annoying. AJAX isn't exactly new! :(

**Comment by dahlbyk** [comment] 2016-03-24 20:52
Agree that it's annoying. We're really just trying to zero in on exactly what the problem is. Firefox _never_ working would likely be some issue separate from all browsers eventually losing socket connections (due to timeout, lost focus, network interruption, etc).

There's no question we need to reestablish lost connections and synchronize boards that missed notifications. We just need to figure out what fix(es) will be most effective.

**Comment by discorick** [comment] 2016-04-11 17:53
Ok I have gathered a list of requirements, here is how I propose we take care of this:

1. Implement a sticky warning toast
  - this should be almost done already, but we are going to need to have the ability to warn about things like API rate limit overages, or "sync" in progress

2. Implement an API rate limit Poller
  - Every minute check the current API rate limit, toast a dismissible warning once reaching critical warnings, and a perma message when the rate limit is exhausted

3. When API rate limits check out, run a diff on browser focus for activities around the parent board, and each linked repo
  - The diff engine could easily be built client side
  - on diffs deemed "to large" toast instructing a board refresh
  - 'grey out' the board on sync to prevent any undesirable out of sync events being fired

Thoughts @dahlbyk @rauhryan ?

**Comment by dahlbyk** [comment] 2016-04-11 18:51
> Every minute check the current API rate limit

By hitting [`/rate_limit`](https://developer.github.com/v3/rate_limit/)?

----

Can you expand a bit on what you mean by a diff engine? Are you planning to use the [Events API](https://developer.github.com/v3/activity/events/#list-issue-events-for-a-repository) to check if we've missed events or...?

From Events docs:

> Events are optimized for polling with the "ETag" header. If no new events have been triggered, you will see a "304 Not Modified" response, and your current rate limit will be untouched. There is also an "X-Poll-Interval" header that specifies how often (in seconds) you are allowed to poll. In times of high server load, the time may increase. Please obey the header.

**Comment by discorick** [comment] 2016-04-11 19:10
Updated with some clarifications.

**Comment by dahlbyk** [comment] 2016-04-11 19:14
This sounds like a good approach to me. Do we have any evidence that individual users are hitting authenticated rate limiting? If not, we could potentially defer Step 2 until we know it's necessary. I'd guess a lot of the time our Events check will return 304 and not count against us (assuming ETag is properly specified!).

**Comment by discorick** [comment] 2016-04-11 21:39
We _could_ kick the can one number Step 2 I suppose, API usage will certainly rise a bit though. I suppose if we come out of testing without incurring and exceeding on of Rate Limits then we don't need to worry about it.

**Comment by dahlbyk** [comment] 2016-04-12 15:34
> I suppose if we come out of testing without incurring an exceeding of Rate Limits then we don't need to worry about it.

Now you have me curious. Not sure exactly how to pull it off, but it would be neat if Ghee had a mechanism to expose the current rate limit value (extracted from response headers) for the current auth token, rather than requiring an explicit request. We could then add a post-request job that tracks the `X-RateLimit-Remaining` so we can get a sense how close real users get to running out.

**Comment by discorick** [comment] 2016-04-12 19:08
> Not sure exactly how to pull it off, but it would be neat if Ghee had a mechanism to expose the current rate limit value (extracted from response headers) for the current auth token, rather than requiring an explicit request. We could then add a post-request job that tracks the X-RateLimit-Remaining so we can get a sense how close real users get to running out.

Dude. Yah. It may not actually be that difficult.

**Closed** 2016-05-03 20:38 UTC
Labels: 3 - In Review, bug
