### ISSUE TITLE
Add Repo To Issue View

### ISSUE THREAD

**Issue by dylanfitz** [huboard/huboard-web#171] opened 2016-01-19 19:35 UTC
I currently use a linked repository to see all issues that are logged on all of my repos. This is fantastic for project management. However, I do not think that color coordinating each issue, based on the repo, is enough. Would it be possible to also put the repo name somewhere in the full details of the issue? Maybe in the right sidebar?

![screen_shot_2016-01-19_at_2_23_44_pm](https://cloud.githubusercontent.com/assets/6518867/12429694/ab5312e4-beb9-11e5-8451-ee9bf6845f3c.jpg)

**Comment by discorick** [comment] 2016-02-01 15:28
Yeah! We really need this. +1

**Comment by discorick** [comment] 2016-08-04 17:17
Duplicate of https://github.com/huboard/huboard/issues/537

**Closed by discorick** 2016-08-04 17:17 UTC
Labels: 4 - Done, enhancement

**Comment by dahlbyk** [comment] 2016-09-21 19:47
This was addressed by https://github.com/huboard/huboard-web/issues/378, which will go live soon.
